### ISSUE TITLE
[Feature]: Integration with Fabric Waystones

### ISSUE THREAD

**Issue by binomial0** [TheIllusiveC4/CurioOfUndying#13]
### What is the new feature or improvement?

The [Fabric Waystones mod](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) adds a Void Totem, which is an improved Totem of Undying. It would be awesome if this mod could support it like a normal totem, making it work in the trinket slot.

**Comment by LordDeatHunter** [comment]
This seems to be broken in the latest version.
Are there any API endpoints I can expose in Fabric Waystones to make things easier on your end?

**Comment by TheIllusiveC4** [comment]
Which is the latest version? 1.19.2, or 1.19.3, or both?

> Are there any API endpoints I can expose in Fabric Waystones to make things easier on your end?

Hmm, I'm not sure. I don't think so, but I'll revisit that subject once I've discovered what has broken.

**Comment by LordDeatHunter** [comment]
1.19.3, using the latest CurseForge versions of both Charm of Undying & Fabric Waystones.

**Comment by TheIllusiveC4** [comment]
I'm finally getting around to this and I can't actually find anything wrong with the integration. Using Charm of Undying 6.2.1+1.19.3, Trinkets 3.5.1, and Fabric Waystones 3.0.7+mc1.19.3, all of the mechanics seem to work correctly. The Void Totem activates from the trinket slot upon death and the teleportation feature works accurately as well.

@LordDeatHunter Can you specify what part of the integration is broken, or if you're seeing something different from your end?

**Comment by binomial0** [comment]
I just tested it again with those versions (Charm of Undying 6.2.1+1.19.3, Trinkets 3.5.1, and Fabric Waystones 3.0.7+mc1.19.3). The main mechanics work, yay!

However, a major feature of the void totem is that it can save you when you fall in the void. This works when you have it in your hand, but does not yet work in the trinket slot.

**Comment by LordDeatHunter** [comment]
The latest version of Fabric Waystones when I left the comment was v3.0.6.
Since it's working on your end, I might've coincidentally fixed whatever the problem was in v3.0.7. I would have to test again when I have time. Thanks for notifying me.

**Comment by TheIllusiveC4** [comment]
The main mechanic works but, as @binomial0 mentioned, there's a bit of a discrepancy in that it doesn't work in the same manner when falling into the void. I've yet to identify why that's the case, but that's one issue that still needs to be fixed on my end.
