### ISSUE TITLE
[Bug]: The mod information isn't matched the game version, here is the crash log.

### ISSUE THREAD

**Issue by MoneySoup008** [TheIllusiveC4/CurioOfUndying#15]
### Minecraft Version

1.19.2

### What happened?

When I started the game, and the crashes/Incompatible log showed up.
The log is shared.

### How do you trigger this bug?

I didn't do anything but just add this mod to my modpack and here you go, crashes.
The first time it showed me that the mod's name can't use $ code, and I had to change it, but now, it shows the version can't use the $ code. I don't know what to do but report. I have no right to change any information about this mod but this blocks me out of the game.

### Loader

Fabric

### Loader Version

Fabric 0.14.9 / Fabric api - 0.63.0+1.19.2

### Mod Version

charm of undying - fabric-6.0.0+1.19.2-sources

### Relevant Log Outputs

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'charmofundying' (charmofundying) ${version} with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'charmofundying' (charmofundying) ${version} requires version ${fabric_mc_version_range} of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by TheIllusiveC4** [comment]
> charm of undying - fabric-6.0.0+1.19.2-sources

You've downloaded the wrong mod file. You need the regular file, but you have the sources one.
