### ISSUE TITLE
[Feature 1.19.2]: Add support for Fabric Waystone's Void Totem

### ISSUE THREAD

**Issue by kingkuys2123** [TheIllusiveC4/CurioOfUndying#19]
### What is the new feature or improvement?

Add support for [Fabric Waystone's](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) void totem :)

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/illusivesoulworks/charmofundying/issues/13
