### ISSUE TITLE
on dedicated server, players can't respawn

### ISSUE THREAD

**Issue by kreezxil** [TheIllusiveC4/CurioOfUndying#2]
on a dedicated server the curio causes the respawned player to be disconnected from their character model and they are not able to play or move because of that.

on a single player world they don't die ever, just like I suspected, it's not just a few uses like you assured me.

**Comment by TheIllusiveC4** [comment]
Please fill out the bug issue template with the relevant information.

**Comment by TheIllusiveC4** [comment]
I cannot reproduce any of these behaviors. The curio shouldn't be affecting respawn behavior as it doesn't touch that part of the code. If the player is respawning, that means they died, which means the curio really didn't even run most of its code at all.

In my testing, I tried both single player and multiplayer instances. The curio works exactly as it should. It prevents the player death once, consumes itself, and then life goes on as normal. It's not "just a few uses", it's usable exactly one time. Without the curio, death functions as normal too.

I'll need more information to go on, so please fill out the bug issue template with the relevant information such as reproduction steps. Also, are you able to reproduce this behavior with only Curios API and Curio of Undying installed?

**Comment by kreezxil** [comment]
removing your mod solved the issue. I tried multiple removals. if you want
a go of it, install "*World of Dragons - A New Age*" then install the curio
of undying. Then go single player, the curio will not go away. that might
help you further.

you can also install the server pack and then join it and see the other
behavior.

**Comment by TheIllusiveC4** [comment]
> removing your mod solved the issue.

This doesn't really mean anything in terms of debugging. It could mean it was solely my mod, or it could mean it was some kind of interaction between my mod and any number of other mods with a lot of ambiguity as to which one is actually causing the issue.

> if you want a go of it, install "*World of Dragons - A New Age*" then install the curio of undying. Then go single player, the curio will not go away.

I installed your modpack and the curio works fine in single player. I killed myself, the totem activated in the curio slot, checked my curio inventory and it was gone. No problems. I really can't reproduce this is any way without more information.

You still have not responded to my previous requests:

1) Please fill out the bug issue template. Also be sure to include any relevant crash or error logs.
2) Can you reproduce this with JUST Curios API and Curio of Undying?

**Comment by kreezxil** [comment]
just close it for now.
