### ISSUE TITLE
Support for friends and foes[Feature]: 

### ISSUE THREAD

**Issue by Mahadbaloch** [TheIllusiveC4/CurioOfUndying#25]
### What is the new feature or improvement?

The totem of illusion and totem of freezing from "Friends and Foes" mod are not supported and do not go into the slot. Can they be added?

**Comment by TheIllusiveC4** [comment]
What kind of effects do those items have?

**Comment by Mahadbaloch** [comment]
Totem of freezing is a regular totem but entity who kills is damaged and frozen effect is given to it(the one from powdered snow)
Totem of illusion is similar to a regular totem, but it gives the player invisibility effect and makes a large amount of exact copies of the player around them which mobs target.

**Comment by TheIllusiveC4** [comment]
It looks like Friends & Foes have added this compatibility on their end.
