### ISSUE TITLE
[Bug]: Quilt crash on startup

### ISSUE THREAD

**Issue by temyy** [TheIllusiveC4/CurioOfUndying#28]
### Minecraft Version

1.20.1

### What happened?

server crashes while starting up, mod works just fine on client but not server

### How do you trigger this bug?

1. launch the server
2. wait

### Loader

Quilt

### Loader Version

Quilt 0.19.2

### API Version

QFAPI 7.0.6/QSL 6.0.4

### Mod Version

Charm of Undying Quilt 6.4.3 1.20.1

### Relevant Log Outputs

https://paste.ee/p/av6JX

**Comment by temyy** [comment]
nevermind, i just found out that it works while only clientside, but its only letting me equip the void totem from https://www.curseforge.com/minecraft/mc-mods/voidtotem-fabric and not letting me equip the vanilla totem

**Comment by TheIllusiveC4** [comment]
The mod should be installed on both client and server, it won't work properly if it's installed only on one side. I've loaded up the mod with your version numbers as listed but I did not see any errors and the server loaded up just fine.

I would suggest making sure that both the client and the server have the mod and Trinkets (which is a required dependency) installed. If that is already the case, then try updating Quilt Loader and QFAPI/QSL. If this is still an issue afterwards, please report back with that crash report.
