### ISSUE TITLE
[Feature]: Add compatibility with the enchanted Totems of Freezing and Illusion from the Biome Makeover mod

### ISSUE THREAD

**Issue by DEAFG0AT** [TheIllusiveC4/CurioOfUndying#29]
### What is the new feature or improvement?

The mod [Biome Makeover](https://www.curseforge.com/minecraft/mc-mods/biome-makeover) adds three totems: the Totem of Freezing (revives you and freezes your enemies for a few seconds), the Enchanted Totem (gives a much greater buff after revival), and the Totem of Illusion (spawns a fake you that your enemies attack until you fake die, and teleports you away a small, but safe, distance)

These totems are very cool and I would love to be able to equip them in the Trinket slot as I am with the original Totem! Thanks for reading!! :)

**Comment by TheIllusiveC4** [comment]
Do you mean the Totems of Freezing and Illusion from the Friends & Foes mod? I've tested this and Biome Makeover only adds the Enchanted Totem, which already has support and can be used in the Trinket Charm slot. Same for the other totems from the other mod. If this is not the case for some reason, let me know and I'll re-open this feature request for further investigation.

**Comment by DEAFG0AT** [comment]
Yes, I did mean friends and foes. I'm playing on a modpack but I don't know how I got those mixed up, sorry
