### ISSUE TITLE
[Bug]: Kicked by WatchDogAnticheat mod

### ISSUE THREAD

**Issue by willis1030** [TheIllusiveC4/CurioOfUndying#32]
### Minecraft Version

1.20.1

### What happened?

WatchDogAnticheat worked well but charmofundying there.
It shows Extra Mods spectrelib. but I don't put it in .minecraft\mods

### How do you trigger this bug?

1.Three mods are there:
charmofundying-forge-6.4.2+1.20.1.jar
curios-forge-5.3.1+1.20.1.jar
WatchDog-AntiCheat-1.20.1-0.1.jar
2.Setting up WatchDog-AntiCheat ready.
3.Start server and play minecraft, then kicked with message "Extra mods: [spectrelib]"
4.Remove charmofundying will be ok.

### Loader

Forge

### Loader Version

forge-1.20.1-47.1.44

### API Version

curios-forge-5.3.1+1.20.1

### Mod Version

charmofundying-forge-6.4.2+1.20.1

**Comment by TheIllusiveC4** [comment]
Charm of Undying comes packaged natively with SpectreLib. Make sure that the same version of Charm of Undying exists on _both_ the server and the client. If it's still missing SpectreLib for some reason, try redownloading your Charm of Undying file or updating to a later version.
