### ISSUE TITLE
[Crash]: Crash on startup on Fabric 1.20.1

### ISSUE THREAD

**Issue by Zano1999** [TheIllusiveC4/CurioOfUndying#33]
### Minecraft Version

1.20.1

### What happened?

Crash on startup

### How do you trigger this bug?

/

### Loader

Fabric

### Loader Version

Fabric loader 0.14.23

### API Version

Fabric API 0.89.3+ 1.20.1

### Mod Version

charmofundying-fabric-6.4.2+1.20.1

### Relevant Log Outputs

Crash report: https://pastebin.com/JH433sRL

Latest log: https://pastebin.com/hPMVjyAq

**Comment by Poopooracoocoo** [comment]
Also see https://github.com/illusivesoulworks/spectrelib/issues/3

Charm of Undying is currently incompatible with Fabric Loader 0.14.23. It needs to update to use the new version of SpectreLib. 

As a workaround, you can downgrade Fabric Loader to 0.14.22.
