### ISSUE TITLE
[Feature]: compatibility with Netherite Totem from Netherite Extras mod

### ISSUE THREAD

**Issue by peow** [TheIllusiveC4/CurioOfUndying#34]
### What is the new feature or improvement?

Netherite Extras has a Totem of Neverdying, it would be interesting to be able to use it in the Charms slot

https://modrinth.com/mod/netherite-extras

i also ask that if you do this, please publish a version compatible with Fabric Loader 0.14.22 (that's where my modpack is)

**Comment by peow** [comment]
will have a 1.20.1 update?

**Comment by TheIllusiveC4** [comment]
Yes.
