### ISSUE TITLE
[Feature]: Support for Friends&Foes and Better Archeology

### ISSUE THREAD

**Issue by 3ncanis** [TheIllusiveC4/CurioOfUndying#36]
### What is the new feature or improvement?

Friends&Foes and Better Archeology both add totems to the game (two each). And I would love support for a player model that shows when you equip them to the Trinkets charm slot. Friends&Foes already has Trinkets support so it would just need a player model for their two totems, and Better Archeology doesn't come with Trinkets support.

**Comment by TheIllusiveC4** [comment]
Unfortunately, I won't be adding Better Archeology support because those totems are quite different from other ones (as they are actively used rather than passively) and would require too much departure from the rest of the codebase to support.
