### ISSUE TITLE
Trinket mods gets me stuck on world generation

### ISSUE THREAD

**Issue by sharpener857** [TheIllusiveC4/CurioOfUndying#4]
#### Versions (Be specific, do not write "latest"):
* Trinket of Undying: 1.1.1-1.16.5
* Curios: 1.16.5-4.0.5.2
* Fabric: 0.11.6
#### Steps to Reproduce: Delete everything install everything again same bug
1. Delete Everything
2. Install Everything
3. And same bug
...

Crash Log: There are no crash logs it just simply gets stuck and the only way to exist is by killing Minecraft

**Comment by TheIllusiveC4** [comment]
This may be due to an outdated Cardinal Components mod. Download/update that mod and retry.
