### ISSUE TITLE
[Feature]: More Configurability

### ISSUE THREAD

**Issue by NextRaven10** [TheIllusiveC4/CurioOfUndying#44]
### What is the new feature or improvement?

I would love to see the config option of disabling the trinket activation and placement for every totem (even from different supported mods) except the ones that are on a list in the config

**Comment by TheIllusiveC4** [comment]
After some thought, this is a little too clunky to implement. Creating a configuration list like this requires navigating around how it currently works, which is through item tags, and item tags are already essentially in a list that can be configured through datapack. It would be more straightforward to use the current method of configuring which items are valid, which is to add/remove entries from the `trinkets:charm/charm` tag or the `curios:charm` tag depending on which API you have installed.
