### ISSUE TITLE
[Feature]: Option to disable the totem rendering

### ISSUE THREAD

**Issue by Dejeh** [TheIllusiveC4/CurioOfUndying#6]
### What is the new feature or improvement?

Hi! Can we have an option to disable the totem rendering on the player's chest? That way it won't overlap with necklaces.

**Comment by TheIllusiveC4** [comment]
Are you talking about the Forge or Fabric version?

**Comment by Dejeh** [comment]
Fabric 1.18

**Comment by Dejeh** [comment]
Any update on this?

**Comment by Tachytaenius** [comment]
I second this, looks weird with Wildfire's Female Gender Mod on lol

**Comment by Tachytaenius** [comment]
Hey, nice
