### ISSUE TITLE
[Feature]: Use slot for modded Totem and other modded accessories.

### ISSUE THREAD

**Issue by ardissaps** [TheIllusiveC4/CurioOfUndying#8]
### What is the new feature or improvement?

It would be nice addition if we can use the slot for modded Totem or other accessories provided by other mods. Thx in advance sir have a nice day.

**Comment by TheIllusiveC4** [comment]
Trinkets API already provides a way to use the slot for other modded totems or accessories. By adding items to the `data/trinkets/tags/items/charm/charm.json` item tag, other accessories or totems can be placed into the slot as well. They may not always work right out of the box, but that integration would be up to the implementing mod to implement themselves through Trinkets API.
